# Generated by Django 2.0.1 on 2018-03-12 00:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('standings', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='race',
            name='point_system',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='standings.PointSystem'),
        ),
    ]
