# Generated by Django 2.0.1 on 2018-03-12 03:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('standings', '0003_auto_20180312_1357'),
    ]

    operations = [
        migrations.AddField(
            model_name='race',
            name='round_number',
            field=models.IntegerField(default=1),
        ),
    ]
