# Generated by Django 2.0.1 on 2018-03-31 00:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('standings', '0005_auto_20180330_0921'),
    ]

    operations = [
        migrations.CreateModel(
            name='LogFile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='')),
                ('race', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='standings.Race')),
            ],
        ),
        migrations.AlterField(
            model_name='pointsystem',
            name='qualifying_points',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='pointsystem',
            name='race_points',
            field=models.CharField(max_length=100),
        ),
    ]
