# Generated by Django 2.0.1 on 2018-03-31 00:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('standings', '0006_auto_20180331_1320'),
    ]

    operations = [
        migrations.AlterField(
            model_name='logfile',
            name='file',
            field=models.FileField(upload_to='log_files/%Y/%m/%d'),
        ),
    ]
