# Generated by Django 2.0.1 on 2018-04-02 01:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('standings', '0010_auto_20180401_1607'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='result',
            name='lap_count',
        ),
        migrations.AlterField(
            model_name='result',
            name='dnf_reason',
            field=models.CharField(blank=True, max_length=50, verbose_name='DNF Reason'),
        ),
        migrations.AlterField(
            model_name='result',
            name='driver',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='standings.Driver'),
        ),
        migrations.AlterField(
            model_name='result',
            name='fastest_lap',
            field=models.BooleanField(default=False, verbose_name='Fastest lap in race'),
        ),
        migrations.AlterField(
            model_name='result',
            name='fastest_lap_value',
            field=models.FloatField(default=0, verbose_name='Fastest lap'),
        ),
        migrations.AlterField(
            model_name='result',
            name='gap',
            field=models.CharField(default='-', max_length=25),
        ),
        migrations.AlterField(
            model_name='result',
            name='points_multiplier',
            field=models.FloatField(default=1, verbose_name='Points Multiplier'),
        ),
        migrations.AlterField(
            model_name='result',
            name='points_multiplier_description',
            field=models.CharField(blank=True, max_length=250, verbose_name='Multiplier Description'),
        ),
        migrations.AlterField(
            model_name='result',
            name='qualifying',
            field=models.IntegerField(default=0, verbose_name='Position'),
        ),
        migrations.AlterField(
            model_name='result',
            name='qualifying_laps',
            field=models.IntegerField(default=0, verbose_name='Lap count'),
        ),
        migrations.AlterField(
            model_name='result',
            name='qualifying_penalty_bog',
            field=models.BooleanField(default=False, verbose_name='Back of grid'),
        ),
        migrations.AlterField(
            model_name='result',
            name='qualifying_penalty_description',
            field=models.CharField(blank=True, max_length=100, verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='result',
            name='qualifying_penalty_grid',
            field=models.IntegerField(default=0, verbose_name='Grid Positions'),
        ),
        migrations.AlterField(
            model_name='result',
            name='qualifying_penalty_sfp',
            field=models.IntegerField(default=0, verbose_name='SFP'),
        ),
        migrations.AlterField(
            model_name='result',
            name='qualifying_time',
            field=models.FloatField(default=0, verbose_name='Total time'),
        ),
        migrations.AlterField(
            model_name='result',
            name='race_laps',
            field=models.IntegerField(default=0, verbose_name='Lap count'),
        ),
        migrations.AlterField(
            model_name='result',
            name='race_penalty_description',
            field=models.CharField(blank=True, max_length=100, verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='result',
            name='race_penalty_positions',
            field=models.IntegerField(default=0, verbose_name='Positions'),
        ),
        migrations.AlterField(
            model_name='result',
            name='race_penalty_time',
            field=models.IntegerField(default=0, verbose_name='Time'),
        ),
        migrations.AlterField(
            model_name='result',
            name='race_time',
            field=models.FloatField(default=0, verbose_name='Total time'),
        ),
        migrations.AlterField(
            model_name='result',
            name='team',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='standings.Team'),
        ),
    ]
