# Generated by Django 2.0.1 on 2018-04-05 02:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('standings', '0012_auto_20180404_0955'),
    ]

    operations = [
        migrations.AlterField(
            model_name='result',
            name='qualifying_penalty_sfp',
            field=models.BooleanField(default=False, verbose_name='SFP'),
        ),
    ]
