# Generated by Django 2.0.1 on 2018-04-11 01:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('standings', '0013_auto_20180405_1435'),
    ]

    operations = [
        migrations.AlterField(
            model_name='result',
            name='qualifying_penalty_sfp',
            field=models.BooleanField(default=False, verbose_name='Start from pits'),
        ),
    ]
