# Generated by Django 2.0.1 on 2018-04-11 08:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('standings', '0014_auto_20180411_1336'),
    ]

    operations = [
        migrations.AlterField(
            model_name='result',
            name='dnf_reason',
            field=models.CharField(blank=True, default='', max_length=50, verbose_name='DNF Reason'),
        ),
    ]
