# Generated by Django 2.0.1 on 2018-04-11 08:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('standings', '0015_auto_20180411_2026'),
    ]

    operations = [
        migrations.AddField(
            model_name='season',
            name='teams_disabled',
            field=models.BooleanField(default=False),
        ),
    ]
