# Generated by Django 2.0.1 on 2018-04-14 03:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('standings', '0018_auto_20180412_1305'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='result',
            name='fastest_lap_value',
        ),
        migrations.AddField(
            model_name='result',
            name='qualifying_fastest_lap',
            field=models.FloatField(default=0, verbose_name='Fastest lap (Q)'),
        ),
        migrations.AddField(
            model_name='result',
            name='race_fastest_lap',
            field=models.FloatField(default=0, verbose_name='Fastest lap (R)'),
        ),
    ]
