# Generated by Django 2.0.1 on 2018-04-13 22:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('standings', '0018_auto_20180412_1305'),
    ]

    operations = [
        migrations.CreateModel(
            name='SeasonPenalty',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('points', models.IntegerField(default=0)),
                ('disqualified', models.BooleanField(default=False)),
                ('driver', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='standings.Driver')),
                ('season', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='standings.Season')),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='standings.Team')),
            ],
        ),
    ]
