# Generated by Django 2.0.1 on 2018-04-14 08:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('standings', '0019_auto_20180414_1502'),
    ]

    operations = [
        migrations.AddField(
            model_name='result',
            name='qualifying_penalty_dsq',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='result',
            name='race_penalty_dsq',
            field=models.BooleanField(default=False),
        ),
    ]
