# Generated by Django 2.0.1 on 2018-04-13 22:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('standings', '0019_seasonpenalty'),
    ]

    operations = [
        migrations.AlterField(
            model_name='seasonpenalty',
            name='driver',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='standings.Driver'),
        ),
        migrations.AlterField(
            model_name='seasonpenalty',
            name='team',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='standings.Team'),
        ),
    ]
