# Generated by Django 2.0.1 on 2018-04-14 02:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('standings', '0021_auto_20180414_1038'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='seasonpenalty',
            options={'verbose_name_plural': 'Season Penalties'},
        ),
        migrations.RemoveField(
            model_name='result',
            name='fastest_lap_value',
        ),
        migrations.AddField(
            model_name='result',
            name='qualifying_fastest_lap',
            field=models.FloatField(default=0, verbose_name='Fastest lap (Q)'),
        ),
        migrations.AddField(
            model_name='result',
            name='race_fastest_lap',
            field=models.FloatField(default=0, verbose_name='Fastest lap (R)'),
        ),
    ]
