# Generated by Django 2.0.4 on 2018-04-25 03:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('standings', '0022_auto_20180425_1534'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='seasonstats',
            options={'verbose_name_plural': 'Season stats'},
        ),
        migrations.AddField(
            model_name='seasonstats',
            name='fastest_laps',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='seasonstats',
            name='laps_completed',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='seasonstats',
            name='laps_lead',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='seasonstats',
            name='podiums',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='seasonstats',
            name='points_finishes',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='seasonstats',
            name='pole_positions',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='seasonstats',
            name='winner',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='seasonstats',
            name='wins',
            field=models.IntegerField(default=0),
        ),
    ]
