# Generated by Django 2.0.4 on 2018-06-17 07:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('standings', '0025_seasonstats_attendance'),
    ]

    operations = [
        migrations.AddField(
            model_name='logfile',
            name='summary',
            field=models.TextField(blank=True, default=''),
        ),
    ]
