# Generated by Django 2.0.4 on 2018-06-25 22:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('standings', '0026_logfile_summary'),
    ]

    operations = [
        migrations.AddField(
            model_name='logfile',
            name='session',
            field=models.CharField(default='', max_length=10),
        ),
    ]
