# Generated by Django 2.0.4 on 2018-07-18 02:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('standings', '0028_team_parent'),
    ]

    operations = [
        migrations.AddField(
            model_name='seasonstats',
            name='best_result',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='standings.Result'),
        ),
        migrations.AlterField(
            model_name='logfile',
            name='session',
            field=models.CharField(blank=True, default='', max_length=10),
        ),
    ]
