# Generated by Django 2.0.4 on 2018-07-18 02:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('standings', '0029_auto_20180718_1415'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='seasonstats',
            name='best_finish',
        ),
    ]
