# Generated by Django 2.0.4 on 2018-07-20 01:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('standings', '0030_remove_seasonstats_best_finish'),
    ]

    operations = [
        migrations.AddField(
            model_name='seasonstats',
            name='penalty_points',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='seasonstats',
            name='qualifying_penalty_bog',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='seasonstats',
            name='qualifying_penalty_dsq',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='seasonstats',
            name='qualifying_penalty_grid',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='seasonstats',
            name='qualifying_penalty_sfp',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='seasonstats',
            name='race_penalty_dsq',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='seasonstats',
            name='race_penalty_positions',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='seasonstats',
            name='race_penalty_time',
            field=models.IntegerField(default=0),
        ),
    ]
