# Generated by Django 2.0.4 on 2018-07-22 03:57

import django.contrib.postgres.fields.jsonb
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('standings', '0033_seasonstats_dnf_reasons'),
    ]

    operations = [
        migrations.AddField(
            model_name='seasonstats',
            name='qualifying',
            field=django.contrib.postgres.fields.jsonb.JSONField(default={}),
        ),
    ]
