# Generated by Django 2.0.7 on 2018-08-13 08:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('standings', '0034_seasonstats_qualifying'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pointsystem',
            name='name',
            field=models.CharField(max_length=50),
        ),
    ]
