# Generated by Django 2.0.7 on 2018-08-15 02:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('standings', '0035_auto_20180813_2034'),
    ]

    operations = [
        migrations.AlterField(
            model_name='result',
            name='car',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='result',
            name='car_class',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
