# Generated by Django 2.0.7 on 2018-08-23 03:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('standings', '0039_auto_20180823_1437'),
    ]

    operations = [
        migrations.AddField(
            model_name='seasonstats',
            name='season_position',
            field=models.IntegerField(default=99),
        ),
    ]
