# Generated by Django 2.0.8 on 2018-10-13 04:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('standings', '0040_seasonstats_season_position'),
    ]

    operations = [
        migrations.CreateModel(
            name='SeasonCarNumber',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('car_number', models.IntegerField(default=0)),
                ('driver', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='standings.Driver')),
                ('season', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='standings.Season')),
            ],
            options={
                'verbose_name_plural': 'Season Car Numbers',
            },
        ),
    ]
