# Generated by Django 2.0.8 on 2018-11-04 22:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('standings', '0041_seasoncarnumber'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='lap',
            options={'ordering': ['lap_number']},
        ),
        migrations.AddField(
            model_name='result',
            name='classified',
            field=models.BooleanField(default=True),
        ),
    ]
