# Generated by Django 2.0.8 on 2018-11-23 07:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('standings', '0042_auto_20181105_1133'),
    ]

    operations = [
        migrations.AddField(
            model_name='result',
            name='point_deduction',
            field=models.IntegerField(default=0),
        ),
    ]
