# Generated by Django 2.0.8 on 2018-12-02 03:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('standings', '0043_auto_20181123_2049'),
    ]

    operations = [
        migrations.AddField(
            model_name='lap',
            name='compound',
            field=models.CharField(blank=True, max_length=10, verbose_name='Tyre Compound'),
        ),
    ]
