# Generated by Django 2.0.9 on 2019-03-11 01:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('standings', '0044_auto_20181202_1602'),
    ]

    operations = [
        migrations.AddField(
            model_name='season',
            name='constructor_max',
            field=models.IntegerField(default=0),
        ),
    ]
