# Generated by Django 2.0.9 on 2019-03-24 02:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('standings', '0045_season_constructor_max'),
    ]

    operations = [
        migrations.AlterField(
            model_name='season',
            name='constructor_max',
            field=models.IntegerField(default=0, help_text='The maximum number of drivers that can score points for their team (0 = disabled)'),
        ),
    ]
