# Generated by Django 2.2 on 2019-04-05 04:04

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('standings', '0046_auto_20190324_1527'),
    ]

    operations = [
        migrations.AlterField(
            model_name='seasonstats',
            name='dnf_reasons',
            field=django.contrib.postgres.fields.jsonb.JSONField(default=dict),
        ),
        migrations.AlterField(
            model_name='seasonstats',
            name='positions',
            field=django.contrib.postgres.fields.jsonb.JSONField(default=dict),
        ),
        migrations.AlterField(
            model_name='seasonstats',
            name='qualifying',
            field=django.contrib.postgres.fields.jsonb.JSONField(default=dict),
        ),
    ]
