# Generated by Django 2.2 on 2019-04-05 04:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('standings', '0047_auto_20190405_1704'),
    ]

    operations = [
        migrations.AlterField(
            model_name='race',
            name='start_time',
            field=models.DateTimeField(db_index=True),
        ),
    ]
