# Generated by Django 2.2 on 2019-04-05 04:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('standings', '0048_auto_20190405_1705'),
    ]

    operations = [
        migrations.AddField(
            model_name='lap',
            name='wear_fl',
            field=models.FloatField(default=0, verbose_name='Wear (Front Left)'),
        ),
        migrations.AddField(
            model_name='lap',
            name='wear_fr',
            field=models.FloatField(default=0, verbose_name='Wear (Front Right)'),
        ),
        migrations.AddField(
            model_name='lap',
            name='wear_rl',
            field=models.FloatField(default=0, verbose_name='Wear (Rear Left)'),
        ),
        migrations.AddField(
            model_name='lap',
            name='wear_rr',
            field=models.FloatField(default=0, verbose_name='Wear (Rear Right)'),
        ),
    ]
