# Generated by Django 2.2 on 2019-04-29 00:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('standings', '0050_driver_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='team',
            name='slug',
            field=models.SlugField(blank=True, max_length=100, null=True, unique=True),
        ),
    ]
