# Generated by Django 3.0.2 on 2020-02-02 22:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('standings', '0051_team_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='race',
            name='abandoned',
            field=models.BooleanField(default=False),
        ),
    ]
