# Generated by Django 3.0.2 on 2020-03-26 00:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('standings', '0052_race_abandoned'),
    ]

    operations = [
        migrations.CreateModel(
            name='SeasonTyreMap',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('c1', models.CharField(max_length=15)),
                ('c2', models.CharField(max_length=15)),
                ('c3', models.CharField(max_length=15)),
                ('c4', models.CharField(max_length=15)),
                ('c5', models.CharField(max_length=15)),
                ('season', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='standings.Season')),
            ],
            options={
                'verbose_name_plural': 'Season Compound Map',
            },
        ),
    ]
