# Generated by Django 2.2.13 on 2020-08-06 06:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('standings', '0053_seasontyremap'),
    ]

    operations = [
        migrations.AddField(
            model_name='division',
            name='slug',
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.AddField(
            model_name='season',
            name='slug',
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.AddField(
            model_name='seasontyremap',
            name='c6',
            field=models.CharField(blank=True, max_length=15),
        ),
        migrations.AddField(
            model_name='seasontyremap',
            name='c7',
            field=models.CharField(blank=True, max_length=15),
        ),
        migrations.AlterField(
            model_name='seasontyremap',
            name='c1',
            field=models.CharField(blank=True, max_length=15),
        ),
        migrations.AlterField(
            model_name='seasontyremap',
            name='c2',
            field=models.CharField(blank=True, max_length=15),
        ),
        migrations.AlterField(
            model_name='seasontyremap',
            name='c3',
            field=models.CharField(blank=True, max_length=15),
        ),
        migrations.AlterField(
            model_name='seasontyremap',
            name='c4',
            field=models.CharField(blank=True, max_length=15),
        ),
        migrations.AlterField(
            model_name='seasontyremap',
            name='c5',
            field=models.CharField(blank=True, max_length=15),
        ),
    ]
