# Generated by Django 2.2.13 on 2020-09-22 20:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('standings', '0054_auto_20200806_0652'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lap',
            name='compound',
            field=models.CharField(blank=True, max_length=20, verbose_name='Tyre Compound'),
        ),
    ]
