# Generated by Django 2.2.18 on 2021-03-27 05:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('standings', '0055_auto_20200922_2017'),
    ]

    operations = [
        migrations.AddField(
            model_name='division',
            name='log_file_tag',
            field=models.CharField(blank=True, max_length=10),
        ),
    ]
