# Generated by Django 2.2.28 on 2022-06-23 21:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('standings', '0056_division_log_file_tag'),
    ]

    operations = [
        migrations.AddField(
            model_name='season',
            name='countback_range',
            field=models.IntegerField(default=10),
        ),
    ]
