# Generated by Django 2.2.28 on 2022-10-14 21:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('standings', '0057_season_countback_range'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pointsystem',
            name='qualifying_points',
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.AlterField(
            model_name='pointsystem',
            name='race_points',
            field=models.CharField(max_length=150),
        ),
        migrations.AlterField(
            model_name='season',
            name='countback_range',
            field=models.IntegerField(default=10, help_text='How far into result positions to count back for tie breaker rules'),
        ),
    ]
